### ISSUE TITLE
Does not work with Ruby 2.0

### ISSUE THREAD

**Issue by lzap** [lzap/gem-ripper-tags#1]
ERROR: Loading command ripper(LoadError). Cannot load such file -- rubygems/commands/ripper_command. ERROR: while executing gem ... (NoMethodError) undefined method 'invoke_with_build_args' for nil:NilClass"

Any suggestions? I installed using

rvm @global do gem install gem-ripper-tags and added to global gemset (.rvm/gemsets/global.gems).﻿
